language: ruby
rvm:
  - 2.6
script: gem build terraorg.gemspec
env:
  global:
    - secure: "fxfjGy/ZyM0UXCatFhMpncEbBwiWjZ7CwvCmZ2uVsBGv8lNldWDs/MAEe2jFI+U+HTOCzL6tIGkdjp8VuA2vAHUd3qKLwjsZogD+DcFvsnxzYS1705eidOvp/d1zxuioA5lY+addrX2fwN4xLCVfBB9bil4w895kLnjnh9D95BI4dNL3k7aZ26KEvMhSu3cLryPPiOi3ZclI+DVhl8il6A2wRQj0nXDyMMyIx7Bu+0qpHV192c5Jn4GFfGQf9NV4HLcZJjHfuvaq5pbytTH1ijirPTgo0tx1Yi1qRhRsUvnxvqxTARD45eZ3Mnr48NRLzXGpNXmpEe8/YGtK+sF3Z+bYkiHcDK9y/VcJI0js064rG8JOO/5cVIweWJB8QHv7Nf2nptpWZIR3KvB5lmAIdjYl4Xomgbv1Usjwpsr41mAGHEO5wxVXyCv6TOMFeHmmiOsvXgzbZ+3xVnLgEiTQE/HbNHPF5x9RgcTZad7lc3bo3KQgLLJqb0jPI5mtmLFDoXhDm2CChECctNlbnW+LufwF2VdAsXz1noPpxCbQ17d+SBj2lllM+1RXHD9Avb0J2UUWSO3fZlVWxLeo/YNiMgyU8bvjFi1n4KSKRTYS5FNZgJ0L4iowDyJ7aKzQi+VJx5Fi39SJTXT8zOv+iVryKk3FyTrsr0AGVi60BPFKBz8="
deploy:
  - skip_cleanup: true
    on:
      - tags: true
    provider: script
    script: .travis/publish
